modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "CC BY-NC-SA 4.0"

[[mods]]
modId = "crystallized"
version = "${version}"
displayName = "Create: Crystallized"
authors = "ReMelon"
description = '''
Create Mod Addon focused on adding more ways to automate various resources through the addition of crystal growing.
'''
logoFile = "icon.png"

[[dependencies.crystallized]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crystallized]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.crystallized]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"